version: '3'
services:
  database:
    image: mysql:5.7
    container_name: database
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=spotifyclone
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'

  api:
    image: 'node:12'
    container_name: api
    volumes:
      - './:/app/'
    working_dir: /app
    command: ./run-local.sh
    environment:
      - NODE_ENV=dev
      - API_PORT=8080
      - DB_HOSTNAME=database
      - DB_DATABASE=spotifyclone
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DIALECT=mysql
      - DB_LOGGING=false
      - ACCESS_TOKEN_SECRET=swsh23hjddnns
      - ACCESS_TOKEN_LIFE=120
      - REFRESH_TOKEN_SECRET=dhw782wujnd99ahmmakhanjkajikhiwn2n
      - REFRESH_TOKEN_LIFE=86400^
    depends_on:
      - database
    ports:
      - '8080:8080'
